### ISSUE TITLE
3400 build status

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [headcrab-garage/Xash3DEx#2]
Status for engine modules that currently buildable by specified compiler version:

| Module | **MinGW** | **MSVC** | **Clang (unsupported yet)** |
| --- | --- | --- | --- |
| Launcher | Yes | Yes |  |
| GameUI (MainUI) | Yes | Yes |  |
| Engine | No | Yes |  |

**Comment by SourcePowered** [comment]
Year! Sir!
And I think we need to put HLSDK in it...

**Comment by Sh1ft0x0EF** [comment]
Almost done, need some additional fixes in hlsdk headers to compile
Use [hlsdk-core](https://github.com/Sh1ft0x0EF/hlsdk-core)
It's meant to be used for both for mod and xash development (+ plugin dev and various other things)
But I still need to fix some things in it
