### ISSUE TITLE
Music not working?

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [headcrab-garage/Xash3DEx#27]
@CrusoeDaWolf:
> It seems like music does not play at all. When starting the game, I cannot hear Prospero1.mp3 (Vauge Voices) play and using the "music" command does nothing at all.

**Comment by Sh1ft0x0EF** [comment]
Which buildnum?

**Comment by CrusoeDaWolf** [comment]
Latest. 3415.

**Comment by Sh1ft0x0EF** [comment]
fixed
