### ISSUE TITLE
VGUIGlue -> MainUI

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [headcrab-garage/Xash3DEx#7]
TODO: Move work with vgui to gameui/menu code
(Engine_Frame->Menu_Frame->VGUI_Frame)

p.s: Is it really possible?

**Comment by CrusoeDaWolf** [comment]
I'm not sure, but I think it probably could be possible. From what I understand, you can still compile Xash3D without needing VGUI. They even have an hlsdk that is vgui-less, so you can most likely do it.

**Comment by Sh1ft0x0EF** [comment]
We need to provide a pointer to root panel to client dll
It would be someway like that if we place vgui_connector code in menu: rootpanel export (whole impl of this module could be optional in menu) ->raw ptr to engine -> raw ptr to clientdll and cast back to vgui panel
But the version of vgui linked with menu should be bin-compat with the clientdll' one
Anyway we need to remove vgui dependency from the engine since it currently unbuildable by MinGW

**Comment by Sh1ft0x0EF** [comment]
Cancelled
